substitutions:
  device_name: frontroom
  friendly_name: frontroom
  device_description: "esp8266 by tv"

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  project:
    name: "jon.frontroom"
    version: "0.0.1"

# Enable logging
esp8266:
  board: d1_mini_lite

logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Frontroom Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

text_sensor:
  - platform: version
    hide_timestamp: true
    name: '${friendly_name} - ESPHome Version'
  - platform: wifi_info
    ip_address:
      name: '${friendly_name} - IP Address'
      icon: mdi:wifi
    ssid:
      name: '${friendly_name} - Connected SSID'
      icon: mdi:wifi-strength-

sensor:
  - platform: wifi_signal
    name: "${friendly_name} - WiFi Signal"
    update_interval: 120s
  - platform: uptime
    name: "${friendly_name} - Uptime"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
    name: "Window Left Bottom"
    id: "window_left_bottom"
    device_class: Window
  - platform: gpio
    pin: 
      number: D2
      mode: INPUT_PULLUP
    name: "Window Left Top"
    id: "window_left_top"
    device_class: Window
  - platform: gpio
    pin: 
      number: D3
      mode: INPUT_PULLUP
    name: "Window Right Bottom"
    id: "window_right_bottom"
    device_class: Window
  - platform: gpio
    pin: 
      number: D4
      mode: INPUT_PULLUP
    name: "Window Right Top"
    id: "window_right_top"
    device_class: Window