esphome:
  name: octoprint_sw
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Relay"
    password: !secret livingroom_relay_ota_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

switch:
  - platform: gpio
    name: "octoprint"
    pin:
      number: 5
      inverted: yes